version: "3.7"
services:
  app:
    build: 
      context: ./php-fpm 
      args:
        - PHP_VERSION=${PHP_FPM_VERSION}
        - user=${USER}
        - uid=${UUID} 
    restart: unless-stopped
    working_dir: ${APP_CODE_PATH_CONTAINER}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}/
    networks:
      - backend

  nginx:
    build: 
      context: ./ngnix
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ../:/var/www/
    depends_on:
      - app
    networks:
      - backend

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_PORT}:3306"
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - backend
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    restart: unless-stopped
    links:
      - mysql
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - app
    networks:
      - backend
  
networks:
  backend:
    driver: bridge
